Infection Hider Inventory:
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: IRON_SWORD
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: STONE_AXE
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: COOKED_BEEF
    amount: 32
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: GOLDEN_APPLE
    amount: 8
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:long_swiftness
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_swiftness
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: COMPASS
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: CHAINMAIL_BOOTS
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: CHAINMAIL_LEGGINGS
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: CHAINMAIL_CHESTPLATE
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: CHAINMAIL_HELMET
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SHIELD
Infection Infected Inventory:
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: DIAMOND_SWORD
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: IRON_AXE
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: COOKED_BEEF
    amount: 32
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: GOLDEN_APPLE
    amount: 8
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:long_swiftness
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_swiftness
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: COMPASS
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SPLASH_POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      potion-type: minecraft:strong_healing
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: IRON_BOOTS
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: IRON_LEGGINGS
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: IRON_CHESTPLATE
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: IRON_HELMET
  - ==: org.bukkit.inventory.ItemStack
    v: 2730
    type: SHIELD