name: Infection
version: '${project.version}'
main: me.mrredness.infection.Infection
api-version: 1.17
description: A Minecraft version of the popular kid's game.
softdepend: [WorldBorder]
commands:
  infection:
    description: 'Join a round of infection or setup the plugin for first use.'
    usage: "Usage: /<command> [join|leave|setup]"